name: Deploy to Firebase Functions on merge
on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed
  #push:
  #  branches:
  #    - main
      
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: 
          npm ci && cd functions && npm ci

      - name: Create env file
        run: |
          cd functions && touch .env && echo FIREBASE_SERVICE_ACCOUNT_CONVERTED=${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONVERTED }} >> .env   

      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} 